name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: "Ejecutar caso de prueba: ${{ matrix.testcase }}"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
      options: --user 1001

    strategy:
      fail-fast: false
      matrix:
        testcase: ["CP1", "CP2", "CP3", "CP4", "CP5", "CP6"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Ejecutar test ${{ matrix.testcase }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" \
          npx playwright test src/tests/cart.spec.ts -g "${{ matrix.testcase }}" \
            --reporter=html \
            --retries=2 \
            --timeout=60000
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.testcase }}
          path: playwright-report/
          retention-days: 30
